/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Collectible__factory } from "./Collectible__factory";
export { Collectible1155__factory } from "./Collectible1155__factory";
